version: '3'
services:
  app:
    container_name: formation-nodejs-app
    image: node:8.4.0
    user: node
    entrypoint: npm
    command: start
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
  mongo:
    container_name: formation-nodejs-mongo
    image: mongo:3.4.7
    # docker exec -it formation-nodejs-mongo mongo admin
    # db.createUser({user: 'openska', pwd: 'openska', roles: [{role: "userAdminAnyDatabase", db: "admin"}]});
